name: Build and Deploy to OKD

on:
  push:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          KUBE_HOST: "https://api.fured.cloud.bme.hu:6443"
          KUBE_TOKEN: ${{ secrets.OKD_TOKEN }}
          KUBE_INSECURE: "true"

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          KUBE_HOST: "https://api.fured.cloud.bme.hu:6443"
          KUBE_TOKEN: ${{ secrets.OKD_TOKEN }}
          KUBE_INSECURE: "true"
          TF_VAR_okd_token: ${{ secrets.OKD_TOKEN }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_django_image: "image-registry.openshift-image-registry.svc:5000/photo-album/django:latest"